- name: copy configuration files
  copy:
    src={{ item }}
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/{{ item }}
    force=no
    mode=644
    owner={{ apache_user }}
    group={{ apache_user }}
  with_items:
    - Skins.php

- name: check out skins from git
  git:
    repo={{ item.url }}
    dest={{ MW_CODE_DIRECTORY }}/skins/{{ item.name }}
    version={{ item.version }}
  with_items: "{{ SKINS }}"

- name: configure skins
  lineinfile:
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Skins.php
    regexp="wfLoadSkin\(\s*['\"]{{ item.name }}['\"]"
    line="wfLoadSkin( '{{ item.name }}' );"
  with_items: "{{ SKINS }}"
  
- name: install Chameleon skin
  shell: composer require "mediawiki/chameleon-skin:~1.0"
  args: 
    chdir: "{{ MW_CODE_DIRECTORY }}"

# This will need to be updated to affect the main LocalSettings.php
- name: make Chameleon the default skin
  lineinfile:
    dest={{ MW_WIKIFARM_CONFIG_DIRECTORY }}/Skins.php
    state=present
    line="$wgDefaultSkin='chameleon';"

