- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  vars_prompt:
    - name: do_name
      prompt: "Name of server to destroy"
      private: no
    - name: do_dns
      prompt: "DNS name to delete"
      private: no
  tasks:
    - name: Delete droplet
      digital_ocean: >
        state=absent
        name={{ do_name }}
        unique_name=yes
        api_token={{ do_api_token }}

    - name: Remove DNS record
      digital_ocean_domain: >
        state=absent
        name="{{ do_dns }}"
        api_token={{ do_api_token }}
      when: do_dns|length > 0
