- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  vars_prompt:
    - name: do_name
      prompt: "Choose a hostname. Give your Droplet an identifying name you will remember it by. Your Droplet name can only contain alphanumeric characters, dashes, and periods. E.g. web2, wiki.example.com, proj-role-datacenter"
      private: no
#    - name: do_dns
#      prompt: "DNS name to bind (press return for none)"
#      private: no
  tasks:
    - name: Register SSH key
      digital_ocean: >
        state=present
        command=ssh
        name="{{ do_ssh_name }}"
        ssh_pub_key="{{ ssh_pub_key }}"
        api_token={{ do_api_token }}
      register: do_droplet
      tags: [digital ocean, bootstrap]

    - name: Register Droplet
      digital_ocean: >
        state=active
        command=droplet
        name={{ do_name }}
        region_id={{ do_region }}
        size_id={{ do_size }}
        image_id={{ do_image }}
        ssh_key_ids={{ do_droplet.ssh_key.id }}
        unique_name=yes
        api_token={{ do_api_token }}
        wait_timeout=600
      register: do_droplet
      tags: [digital ocean, bootstrap]

    - name: Register DNS
      digital_ocean_domain: >
        state=present
        name="{{ do_dns }}"
        id="{{ do_droplet.droplet.id }}"
        api_token={{ do_api_token }}
      when: do_dns|length > 0
      tags: [digital ocean, bootstrap]

    - debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
      tags: [digital ocean, bootstrap, message]
      
    - name: Add new droplet to inventory
      add_host: >
        name="{{ do_name }}"
        groups=mw_hosts
        ansible_ssh_host="{{ do_droplet.droplet.ip_address }}"
        tags: [digital ocean, bootstrap]
    - name: Record hostname for other plays
      set_fact:
        wiki_hostname: "{{ do_name }}"
        
    - debug: msg="You're new droplet has been launched. Add it to your hosts file with {{wiki_hostname}} ansible_host={{ do_droplet.droplet.ip_address }}  Then run ansible-playbook provision.yml --extra-vars 'wiki_hostname={{wiki_hostname}} apache_user=www-data'"
        
### need these for xenial  
#    - name: apt-get update
#      raw: apt-get update -qq 
#    - name: Install python 2.7 
#      raw: apt-get install -qq python2.7 