- hosts: mw_hosts
  # use strategy: debug when you want to debug your playbook
  # strategy: debug
  remote_user: root
  gather_facts: no

  vars_files:
    - defaults/main.yml
    - vars.yml

  pre_tasks:
    - name: Record hostname if not defined
      set_fact:
        wiki_hostname: "{{ inventory_hostname }}"
      when: wiki_hostname is undefined
      # host={{ wiki_hostname | default(inventory_hostname) }}
    - name: Wait for new host to come up
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=0
      tags: [connect]
    - setup:
    - include: tasks/swap.yml
      tags: [whitebox, disk]
    - include: tasks/software.yml
      tags: [whitebox, packages]
    - include: tasks/security.yml
      tags: [whitebox, security]
    - include: tasks/users.yml
      tags: [whitebox, users]

  handlers:
    - include: handlers/site.yml  
  
  # install all the goodness
  roles:
    - { role: qualitybox, tags: ["qualitybox", "mediawiki"] }
    - { role: install_git, tags: ["qualitybox", "mediawiki"] }
    - { role: deploy_mw_host, tags: ["qualitybox", "mediawiki"] }

# Add more plays to the playbook
- include: install_mediawiki.yml
- include: install_extensions.yml
- include: install_skins.yml
# finally create the wiki
#  - include: create_new_wiki.yml
#  - vars: WIKI_NAME=slicerwiki
