- name: install lua packages
  package:
    name={{ item }}
    state=latest
  with_items:
    - lua5.2
    - liblua5.2-dev
    - luajit

- name: check out luasandbox from git
  git:
    repo={{ MW_LUASANDBOX_GIT_URL }}
    dest=/usr/src/luasandbox
    version=master

- name: compile and install luasandbox
  shell: phpize && ./configure --prefix=/usr/lib/php5 && make all install
  args:
    chdir: /usr/src/luasandbox

# This would probably be handled by the 'make' on Ubuntu
- name: copy luasandbox initialization file
  copy:
    src=luasandbox.ini
    dest=/etc/php5/apache2/conf.d/luasandbox.ini
    mode=0600
    owner=root
