---

- name: Install unattended-upgrades
  apt: name={{item}}
    state=latest
    update_cache=yes
    force=yes
  with_items:
    - unattended-upgrades

- name: Overwrite /etc/apt/apt.conf.d/10periodic
  template: src=10periodic.j2 dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=0644