---

- name: Install Python apt packages
  apt: name={{item}}
    state=latest
    update_cache=yes
    force=yes
  with_items:
    - python-mysqldb
    - python-pip
    - python-boto
    - python-pycurl
    - python-dev
    - python-lxml
    - python-yaml

- name: Install Python libraries
  pip: name={{item}}
  with_items:
    - mwclient