---

- name: Install Apache
  package : name={{ item }} 
    state=latest
  with_items:
    - "{{ apache }}"
    - libapache2-mod-auth-mysql
  
- name: Activate mod rewrite
  apache2_module: state=present name=rewrite
  notify: Start Apache2

#https://httpd.apache.org/docs/current/mod/mod_vhost_alias.html
- name: Activate mod_vhost_alias
  apache2_module: state=present name=vhost_alias
  notify: Start Apache2
  
- name: Install Pear packages
  command: pear install {{ item }}
  with_items:
    - Mail
    - Net_SMTP
    - Image_GraphViz

- name: Refresh Pear
  shell: yes '' | pear clear-cache && pear update-channels && pear upgrade

- name: Install Pecl yaml package
  shell: yes '' | pecl install yaml

- name: Add extension=yaml.so to php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini line=extension=yaml.so