---

- name: Remove Ruby
  apt: name={{item}} state=absent
  with_items:
    - ruby1.9.1
    - ruby1.8
    - ruby2.0
    - ruby2.2

- name: Install Ruby
  apt: name={{item}}
    state=latest
    update_cache=yes
    force=yes
  with_items:
    - ruby2.3
    - ruby2.3-dev
    - rubygems