---

- name: Install Apache
  package : name={{ item }} 
    state=latest
  with_items:
    - "{{ apache }}"
    - libapache2-mod-auth-mysql
    - apachetop
    - apache2-utils
  
- name: Activate mod rewrite
  apache2_module: state=present name=rewrite
  notify: Start Apache2

#https://httpd.apache.org/docs/current/mod/mod_vhost_alias.html
- name: Activate mod_vhost_alias
  apache2_module: state=present name=vhost_alias
  notify: Start Apache2
