- name: create root directory
  file:
    state=directory
    path={{ ROOT_DIRECTORY }}
    mode=0775
    owner=root
    group=root

- name: create backup directory
  file:
    state=directory
    path={{ CLONE_DIRECTORY }}
    mode=0775
    owner=root
    group=root


- name: create MediaWiki directory
  file:
    state=directory
    path={{ item }}
    mode=2775
    owner=apache
    group=apache
  with_items:
    - "{{ MW_DIRECTORY }}"
    - "{{ MW_INSTANCE_DIRECTORY }}"
