# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: QualityBox
author: Greg Rundlett
email: info@equality-tech.com
description: > # this means to ignore newlines until "baseurl:"
  QualityBox is a complete, turn-key, production-ready, feature-rich hosted
  solution to Enterprise Knowledge Management.  Based on the MediaWiki 
  platform.  It is totally free software licensed under the GNU Affero license.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://freephile.github.io" # the base hostname & protocol for your site
twitter_username: eQualityTech
github_username:  freephile
# Add in Google Analytics (in production)
google_analytics: UA-39339059-2

# Build settings
markdown: kramdown
# theme: jekyll-theme-modernist
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: "" # an emtpy string here means all files in the project
    values:
      layout: "default" # add the default layout to all pages/posts
